// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "RiffNode",
    platforms: [
        .macOS("14.0"),
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "RiffNode",
            targets: ["AppModule"],
            bundleIdentifier: "com.yujia.RiffNode",
            teamIdentifier: "GJRVCWA2U3",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .mac
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .microphone(purposeString: "RiffNode needs microphone access to process your guitar input through the effects chain.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
